---
title: "Projects"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, include=FALSE}
library(htmltools)
source("R/create_proj_card.R")
```

```{r}
create_proj_card(
  img_src = "img/plots.png",
  url = "https://marwin.shinyapps.io/model-selection-app/",
  title = "Model Selection Bias App",
  text = "This Shiny app is designed for performing simulations of statistical inferences after model selection procedures. Its purpose is to illustrate the problems that arise when model selection, parameters estimation and statistical inferences are undertaken with the same data set.",
  text2 = "Authors: Carmo, M. M. I. B., & Williams, D. R."
)

```

```{r}
create_proj_card(
  img_src = "img/py.jpg",
  url = "https://github.com/marwincarmo/dataquest-projects",
  title = "Data Science projects in Python",
  text = "This is a repository of my work on guided projects from Data Analyst in Python path from Dataquest",
  text2 = ""
)

```

```{r}
create_proj_card(
  img_src = "img/cnpq2.jpg",
  url = "https://marwin.shinyapps.io/bolsas-cnpq/",
  title = "Brazilian Research Funding App",
  text = "In this app I explore the open database of the National Council for Scientific and Technological Development (CNPq),
  a Brazilian Governmnet research funding agency. The user is able to explore data from 18 years of funding destined to students of all levels, as well as funding for research projects.",
  text2 = "Note: the app is in portuguese (english version coming soon)."
)

```

```{r}
create_proj_card(
  img_src = "img/mplogo2.png",
  url = "https://measuringpsychology.netlify.app/",
  title = "Measuring Psychology",
  text = "Measuring Psychology is a global community and study group of people interest in measurement theory for psychology and psychometrics. The community is administred by Marwin Carmo and Rafael Bastos.",
  text2 = ""
)

```