---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: rap-latex-cv.tex
geometry: margin=.75in

title: "CV"
author: Marwin Machay Indio do Brasil do Carmo
#orcid: "orcid.org/0000-0002-9577-6885"
#jobtitle: "Computer Scientist & United States Navy Rear Admiral"
#address: "Address · Arlington · VA 22205"
fontawesome: yes
email: marwinbr@gmail.com
github: marwincarmo
#phone: "+55 21 96525 6044"
web: 'marwincarmo.github.io'
updated: yes

keywords: RMarkdown, academic CV, template

#fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 10pt
linkcolor: blue
urlcolor: blue
---

# EDUCATION
\hrule
**University of São Paulo**, M.Sc. Psychiatry \hfill 2021-- current  
*Area of Study*: Sleep-related cognitions, Quantitative Methods, Psychometrics  
*Advisor*: Renatha El-Rafihi Ferreira, Ph.D  
*Research goal*: Cross-cultural adaptation of the *Dysfunctional Beliefs About Sleep* and *Sleep and Action Questionnaire*. Explore the psychometric properties of both measures utilizing factor analysis and item response theory. Explore associations between sleep related cognitions and insomnia with network analysis.

**Rio de Janeiro State University**, B.S. Psychology  (with honours) \hfill 2014--2019

**Federal Institute of Education, Science and Technology**, B.Tech. Chemical Processes \hfill 2008--2013

# EXPERIENCE
\hrule
**Psicometria Online Academy** \hfill May 2022 -- current  
*Student support* \hfill Brazil  

Answer students' questions to lectures videos related to univariate and multivariate data analysis, structural equation modeling, item response theory and research methods.

**PsicoDados**  \hfill January 2022 -- current  
*Statistical Consultant* \hfill Brazil

Provided statistical consultancy and wrote reports of results in addition to support with executing research and analyses.
 
**Psychology of Human Development Laboratory - UERJ** \hfill August 2019 -- August 2020  
*Research Assistant* \hfill Rio de Janeiro, Brazil
 
- Led on data collection, management and analysis.
- Wrote journal articles and conference presentations.
- Maintained lab website feeding it with information about scientific production.

**Socio-Emotional Development, Inclusion and Social Skills Laboratory - UERJ** \hfill July 2017--July 2019  
*Undergraduate Student Project* \hfill Rio de Janeiro, Brazil

- Conducted Parental Social Skills Training
- Provided support for data collection and management, analysis, and manuscript writing.

**Biodegradable Polymer Research Laboratory - UFRJ** \hfill June 2011--March 2013  
*Undergraduate Student Project* \hfill Rio de Janeiro, Brazil


# Honors Awards and Funding

# RESEARCH FUNDING

**Sao Paulo Research Foundation (FAPESP)** \hfill June 2021

- Title: Adaptação Transcultural e Validação das Escalas Crenças e Atitudes Disfuncionais Sobre o Sono e Questionário de Aceitação dos Problemas de Sono

- Funding: R$ 55,594.44

# PUBLICATIONS
\hrule
## **Journal Articles**

1. Quiterio, P. L., Nunes, L. R. O. P., Camelo, B. L., Silva, J. P., & **Carmo, M. M. I. B.** (2021). Promoção das Habilidades Sociais de Futuros Professores com foco na Educação Inclusiva. *Estudos e Pesquisa em Psicologia*. 

2. Quiterio, P. L., Leme, V. B. R., **Carmo, M. M. I. B.**, Silva, J. P., & Camelo, B. L. (2021). Programa de orientação familiar desenvolvido no serviço de psicologia aplicada de uma universidade pública. *Psicologia Clínica*. 

3. **Carmo, M. M. I. B.**, Gilla, C. G., & Quiterio, P. L. (2020). Um estudo sobre a inclusão de pessoas com deficiência no mercado de trabalho brasileiro. *Interação em Psicologia*. 

4. Ferreira, W. H., **Carmo, M. M. I. B.**, Silva, A. L. N., & Andrade, C. T. (2014). Effect of structure and viscosity of the components on some properties of starch-rich hybrid blends. *Carbohydrate polymers*. 

# SELECTED PRESENTATIONS
\hrule
**Carmo, M. M. I. B.**. (2022). Understanding model selection bias via simulation. VI International Seminar on Statistics with R. [[slides](https://marwincarmo.github.io/slides/vi-ser/selection-bias)]

**Carmo, M. M. I. B.**, & Rafihi-Ferreira, R. (2022).  A network approach of Insomnia and Dysfunctional Beliefs and Attitudes About Sleep. VII Congresso Clínica Psiquiátrica. [[slides](https://marwincarmo.github.io/slides/viiccp/dbas-network_slides)]

**Carmo, M. M. I. B.**, & Rafihi-Ferreira, R. (2022).  Network structure of acceptance of sleep difficulties and insomnia. VII Congresso Clínica Psiquiátrica. [[poster](https://marwincarmo.github.io/posters/poster_viicp_spaq)]

**Carmo, M. M. I. B.**, & Rafihi-Ferreira, R. (2021). The association between sleep-related cognitions, psychological flexibility, and insomnia symptoms. XVIII Congresso Brasileiro de Sono, São Paulo, Brazil. \underline{Recipient of Top Mark Award} [[poster](https://marwincarmo.github.io/posters/cb_sono_poster)]

Conway, B. A., **Carmo, M. M. I. B.**, Toscanini, A. C., Hasan, R., & Rafihi-Ferreira, R. (2021). Personality Traits in Adults with Chronic Insomnia. XVIII Congresso Brasileiro de Sono, São Paulo, Brazil. \underline{Recipient of Top Mark Award}

Cunha, R. R. B. , Trigo, L. O., **Carmo, M. M. I. B.**, Rafihi-Ferreira, R., & Toscanini, A. C. (2021). Chronotype Influence on the Sleep Pattern and Physical/Academic Performance of Medical Students in the State of São Paulo, Brazil. XVIII Congresso Brasileiro de Sono, São Paulo, Brazil.

Trigo, L. O., Cunha, R. R. B. , **Carmo, M. M. I. B.**, Rafihi-Ferreira, R., & Toscanini, A. C. (2021). Sleep Pattern, Cellphone Use and Grade Point Average in São Paulo Medical Students. XVIII Congresso Brasileiro de Sono, São Paulo, Brazil.

Silva, D. A., Souza, J. F., **Carmo, M. M. I. B.**, Quiterio, P. L. (2021). Programas de orientação familiar: intervenções com populações clínicas e não clínicas. 51ª Reunião Anual da Sociedade Brasileira de Psicologia, Rio de Janeiro, Brazil.

**Carmo, M. M. I. B.**, Quiterio, P. L., Silva, J. P., & Camelo, B. L. (2019) Efeitos de Uma Intervenção de Orientação Familiar em Contexto Preventivo e Remediativo. *VII Seminário Internacional de Habilidades Sociais*, Maranhão, Brazil. \underline{Recipient of 3rd place of the Almir Del Prette Award}

Silva, J. P., Quiterio, P. L., **Carmo, M. M. I. B.**, & Souza, A. B. M. (2019) A Importância do Desenvolvimento de Competências Socioemocionais em Pais e Crianças. *VII Seminário Internacional de Habilidades Sociais*, Maranhão, Brazil.

**Carmo, M. M. I. B.**, Quiterio, P. L. (2019). Grupo de Orientação Familiar: uma abordagem integrativa de psicoeducação. *29ª UERJ Sem Muros*, Rio de Janeiro, Brazil.

**Carmo, M. M. I. B.**, Gilla, C. G., & Quiterio, P. L. (2018). Um estudo sobre a inclusão de pessoas com deficiência no mercado de trabalho brasileiro. 12ª Mostra Regional de Práticas em Psicologia, Rio de Janeiro, Brazil.

**Carmo, M. M. I. B.**, Camelo, B. L., Silva, J. P., & Quiterio, P. L. (2018). Avaliação de um Grupo de Orientação Familiar. VII Congresso Brasileiro de Terapia Cognitiva da Infância e Adolescência, Bahia, Brazil. \underline{Recipient of 3rd place in Best Posters Award}

# HONORS & AWARDS

1. VII Congresso Clínica Psiquiátrica, Best Oral Presentation Award \hfill May 2022
2. Congresso Brasileiro de Sono, Poster recipient of Top Mark Award \hfill December 2021
3. VII Seminário Internacional de Habilidades Sociais, 3rd place for Best Poster Award \hfill December 2019
4. VII CONCRIAD, 3rd place for Best Poster Award \hfill November 2018

# SKILLS

*Programming*: R (proficient), Python (familiar)

*Tools*: Git, R Shiny, R markdown, LaTeX (familiar), SPSS, JASP, JAMOVI, Zotero, REDCap

*Statistics Training*

# RELEVANT ACTIVITIES

Organizer of [Measuring Psychology Study Goup and Community](https://measuringpsychology.netlify.app/)

# SOFTWARE DEVELOPMENT

**Carmo, M. M. I. B.**, Williams, D. R. (2021). *Model selection app*. Retrievable from https://marwin.shinyapps.io/model-selection-app/

# RELEVANT COURSEWORK
\hrule
*Mathematics, Statistics & Computer Science*  
Multivariable Calculus, Linear Algebra, Statistical Modeling, Probability Theory, Introduction to Bayesian Data Analysis.

# BLOGS

**Carmo, M. M. I. B.** (2022). Simulating post selection inference. Retrievable from https://marwincarmo.github.io/posts/2021-12-20-model-selection-bias/

**Carmo, M. M. I. B.** (2021). Regression Artifact - Re-running Farmus et. al (2019). Retrievable from https://marwincarmo.github.io/posts/2021-11-04-simulating-regression-artifact/