---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: rap-latex-cv.tex
geometry: margin=.75in

title: "CV"
author: Marwin Machay Indio do Brasil do Carmo
#orcid: "orcid.org/0000-0002-9577-6885"
#jobtitle: "Computer Scientist & United States Navy Rear Admiral"
#address: "Address · Arlington · VA 22205"
fontawesome: yes
email: marwinbr@gmail.com
github: marwincarmo
twitter: marwincarmo
#phone: "+55 21 96525 6044"
web: 'marwincarmo.github.io'
updated: yes

keywords: RMarkdown, academic CV, template

#fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 10pt
linkcolor: blue
urlcolor: blue
---

# EDUCATION
\hrule
**University of São Paulo**, M.Sc. Psychiatry \hfill 2021--current  
*Area of Study*: Sleep-related cognitions, Quantitative Methods, Psychometrics  
*Advisor*: [Renatha El-Rafihi Ferreira, Ph.D.](https://scholar.google.com.br/citations?hl=pt-BR&user=sLWIwcoAAAAJ)  
*Research goal*: Cross-cultural adaptation of the *Dysfunctional Beliefs About Sleep* and *Sleep and Action Questionnaire*. Explore the psychometric properties of both measures utilizing factor analysis and item response theory. Explore associations between sleep related cognitions and insomnia with network analysis.

**Rio de Janeiro State University**, B.S. Psychology  (with honours) \hfill 2014--2019

**Federal Institute of Education, Science and Technology**, B.Tech. Chemical Processes \hfill 2008--2013

# EXPERIENCE
\hrule
**Psicometria Online Academy** \hfill May 2022--current  
*Teaching Assistant* \hfill Rio de Janeiro, Brazil (*remote*)  

- Provided support to students' questions in topics such as general linear models, multivariate statistics, structural equation modeling, factor analysis, item response theory and research methods.

**[Measuring Psychology Study Goup and Community](https://measuringpsychology.netlify.app/)** \hfill February 2022--current  
*Founder and facilitator* \hfill Online

- Organized meetings and led study sessions on measurement theory in psychology with worldwide researchers
- Orchestrated invited presentations by Dr. Derek C. Briggs, Dr. Laura F. Bringmann, Dr. Markus I. Eronen, and Dr. Elina Vessonen.

**PsicoDados**  \hfill January 2022--current  
*Statistical Consultant* \hfill Rio de Janeiro, Brazil (*remote*)

- Provided statistical consultancy and wrote reports of results 
- Provided support with executing research and analyses 
- Delivered teaching sessions on applied statistics for academic researchers
 
**Psychology of Human Development Laboratory - UERJ** \hfill August 2019--August 2020  
*Research Assistant* \hfill Rio de Janeiro, Brazil

- Conducted a systematic review about Brazilian research on social skills training with people with disabilities.
- Performed statistical analysis on research data.
- Delivered introductory statistics workshops to laboratory members.
- Wrote journal articles and gave conference presentations.

**Socio-Emotional Development, Inclusion and Social Skills Laboratory - UERJ** \hfill July 2017--July 2019  
*Undergraduate Research Project* \hfill Rio de Janeiro, Brazil

- Provided support for data collection and management, analysis, and manuscript writing.
- Teaching Assistant at Psychology and Disabilities class.

**Biodegradable Polymer Research Laboratory - UFRJ** \hfill June 2011--March 2013  
*Undergraduate Research Project* \hfill Rio de Janeiro, Brazil

# PUBLICATIONS
\hrule
## **Journal Articles**  
 \* *denotes manuscript in Portuguese*

1. \*Quiterio, P. L., Nunes, L. R. O. P., Camelo, B. L., Silva, J. P., & **Carmo, M. M. I. B.** (2021). Promoting the social skills of future teachers focusing on inclusive
education. *Estudos e Pesquisa em Psicologia*. https://doi.org/10.12957/epp.2021.61060

2. \*Quiterio, P. L., Leme, V. B. R., **Carmo, M. M. I. B.**, Silva, J. P., & Camelo, B. L. (2021). Family guidance program developed in the applied psychology service of a public university. *Psicologia Clínica*. http://dx.doi.org/10.33208/PC1980-5438v0033n01A06 

3. \***Carmo, M. M. I. B.**, Gilla, C. G., & Quiterio, P. L. (2020). A study about the inclusion of people with disabilities in the brazilian labour market. *Interação em Psicologia*. http://dx.doi.org/10.5380/psi.v24i1.59972

4. Ferreira, W. H., **Carmo, M. M. I. B.**, Silva, A. L. N., & Andrade, C. T. (2014). Effect of structure and viscosity of the components on some properties of starch-rich hybrid blends. *Carbohydrate polymers*. https://doi.org/10.1016/j.carbpol.2014.10.018

## **Blogs**

1. **Carmo, M. M. I. B.** (2022). Simulating post selection inference. Retrievable from https://marwincarmo.github.io/posts/2021-12-20-model-selection-bias/

2. **Carmo, M. M. I. B.** (2021). Regression Artifact - Re-running Farmus et. al (2019). Retrievable from https://marwincarmo.github.io/posts/2021-11-04-simulating-regression-artifact/

# SOFTWARE DEVELOPMENT
\hrule
**Model selection app**. A Shiny app designed for performing simulations of statistical inferences after model selection procedures. Its purpose is to illustrate the problems that arise when model selection, parameters estimation and statistical inferences are undertaken with the same data set. [[App](https://marwin.shinyapps.io/model-selection-app/)] [[code](https://github.com/marwincarmo/model-selection-app)]

**Brazilian Research Funding app**. In this app I explore the open database of the National Council for Scientific and Technological Development (CNPq), a Brazilian Government research funding agency. 
[[App](https://marwin.shinyapps.io/bolsas-cnpq/)] [[code](https://github.com/marwincarmo/shiny-bolsas)]

# SKILLS
\hrule
*Programming* 

- R: exploratory data analysis, data cleaning, data visualization, statistical data analyses, programmatic reporting (RMarkdown), web scraping, Shiny apps development, dashboards.
- Python: exploratory data analysis, data cleaning, data visualization.

*Tools* 

- Statistical softwares: R, SPSS, JASP, JAMOVI
- Reporting: RMarkdown, \LaTeX (familiar)
- Version control: Git
- Reference management: Zotero
- Data collection and management: REDCap

# RELEVANT COURSEWORK
\hrule
*Mathematics & Statistics*  
Multivariable Calculus, Linear Algebra, Probability Theory, Machine Learning, Intermediate Statistical Methods, Structural Equation Modeling, Introduction to Bayesian Data Analysis.

*Research Methods*  
Research Methods in Psychotherapy, Epidemiological Methods in Psychiatry, Scientific Writing.

# HONORS & AWARDS
\hrule
1. VII Congresso Clínica Psiquiátrica, Best Oral Presentation Award \hfill May 2022
2. XVIII Congresso Brasileiro de Sono, Poster recipient of Top Mark Award \hfill December 2021
3. VII Seminário Internacional de Habilidades Sociais, 3rd place for Best Poster Award \hfill December 2019
4. VII CONCRIAD, 3rd place for Best Poster Award \hfill November 2018

# SELECTED PRESENTATIONS
\hrule
1. **Carmo, M. M. I. B.**. (2022). Understanding model selection bias via simulation. VI International Seminar on Statistics with R (Online Conference). [[slides](https://marwincarmo.github.io/slides/vi-ser/selection-bias)][[video](https://www.youtube.com/watch?v=eyd1VCAX864&t=910s)]

2. **Carmo, M. M. I. B.**, & Rafihi-Ferreira, R. (2022).  A network approach of Insomnia and Dysfunctional Beliefs and Attitudes About Sleep. VII Congresso Clínica Psiquiátrica, São Paulo, Brazil. [[slides](https://marwincarmo.github.io/slides/viiccp/dbas-network_slides)]

3. **Carmo, M. M. I. B.**, & Rafihi-Ferreira, R. (2022).  Network structure of acceptance of sleep difficulties and insomnia. VII Congresso Clínica Psiquiátrica, São Paulo, Brazil. [[poster](https://marwincarmo.github.io/posters/poster_viicp_spaq)]

4. **Carmo, M. M. I. B.**, & Rafihi-Ferreira, R. (2021). The association between sleep-related cognitions, psychological flexibility, and insomnia symptoms. XVIII Congresso Brasileiro de Sono, São Paulo, Brazil. [[poster](https://marwincarmo.github.io/posters/cb_sono_poster)] [[abstract](https://sono2021.com.br/evento/sono2021/trabalhosaprovados/naintegra/1047)]

5. Conway, B. A., **Carmo, M. M. I. B.**, Toscanini, A. C., Hasan, R., & Rafihi-Ferreira, R. (2021). Personality Traits in Adults with Chronic Insomnia. XVIII Congresso Brasileiro de Sono, São Paulo, Brazil. [[abstract](https://sono2021.com.br/evento/sono2021/trabalhosaprovados/naintegra/1058)]

6. Cunha, R. R. B. , Trigo, L. O., **Carmo, M. M. I. B.**, Rafihi-Ferreira, R., & Toscanini, A. C. (2021). Chronotype Influence on the Sleep Pattern and Physical/Academic Performance of Medical Students in the State of São Paulo, Brazil. XVIII Congresso Brasileiro de Sono, São Paulo, Brazil. [[abstract](https://sono2021.com.br/evento/sono2021/trabalhosaprovados/naintegra/1092)]

7. Trigo, L. O., Cunha, R. R. B. , **Carmo, M. M. I. B.**, Rafihi-Ferreira, R., & Toscanini, A. C. (2021). Sleep Pattern, Cellphone Use and Grade Point Average in São Paulo Medical Students. XVIII Congresso Brasileiro de Sono, São Paulo, Brazil. [[abstract](https://sono2021.com.br/evento/sono2021/trabalhosaprovados/naintegra/1111)]

8. Silva, D. A., Souza, J. F., **Carmo, M. M. I. B.**, Quiterio, P. L. (2021). Programas de orientação familiar: intervenções com populações clínicas e não clínicas. 51ª Reunião Anual da Sociedade Brasileira de Psicologia, Rio de Janeiro, Brazil.

9. **Carmo, M. M. I. B.**, Quiterio, P. L., Silva, J. P., & Camelo, B. L. (2019) Efeitos de Uma Intervenção de Orientação Familiar em Contexto Preventivo e Remediativo. *VII Seminário Internacional de Habilidades Sociais*, Maranhão, Brazil.

10. Silva, J. P., Quiterio, P. L., **Carmo, M. M. I. B.**, & Souza, A. B. M. (2019) A Importância do Desenvolvimento de Competências Socioemocionais em Pais e Crianças. *VII Seminário Internacional de Habilidades Sociais*, Maranhão, Brazil.

11. **Carmo, M. M. I. B.**, Quiterio, P. L. (2019). Grupo de Orientação Familiar: uma abordagem integrativa de psicoeducação. *29ª UERJ Sem Muros*, Rio de Janeiro, Brazil.

12. **Carmo, M. M. I. B.**, Gilla, C. G., & Quiterio, P. L. (2018). Um estudo sobre a inclusão de pessoas com deficiência no mercado de trabalho brasileiro. 12ª Mostra Regional de Práticas em Psicologia, Rio de Janeiro, Brazil.

13. **Carmo, M. M. I. B.**, Camelo, B. L., Silva, J. P., & Quiterio, P. L. (2018). Avaliação de um Grupo de Orientação Familiar. VII Congresso Brasileiro de Terapia Cognitiva da Infância e Adolescência (CONCRIAD), Bahia, Brazil.

# FELLOWSHIPS AND FUNDING
\hrule

1. Master’s Fellowship, Sao Paulo Research Foundation (FAPESP): US$ 11,750.00 \hfill 2021--2023

2. Training and Technical Qualification, Rio de Janeiro Research Foundation (FAPERJ): US$ 2,200.00 \hfill 2019--2020

3. UERJ's Department of Scholarships funding for undergraduate research project: US$ 2,000.00 \hfill 2017--2019
