---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: rap-latex-cv.tex
geometry: margin=1in

title: "CV"
author: Marwin Machay Indio do Brasil do Carmo
#orcid: "orcid.org/0000-0002-9577-6885"
#jobtitle: "Computer Scientist & United States Navy Rear Admiral"
#address: "Address · Arlington · VA 22205"
fontawesome: yes
email: marwinbr@gmail.com
github: marwincarmo
#phone: "+1 555 5555"
web: 'marwincarmo.github.io'
updated: yes

keywords: RMarkdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 10pt
linkcolor: blue
urlcolor: blue
---

# EDUCATION

*University of São Paulo*, M.Sc. Psychiatry \hfill 2021--
  
  > Funded by Sao Paulo Research Foundation (FAPESP)

*Rio de Janeiro State University*, B.S. Psychology \hfill 2014--2019

*Federal Institute of Education, Science and Technology*, B.Tech. Chemical Processes \hfill 2008--2013

# EXPERIENCE

*PsicoDados:*

 > Statistical Consulting \hfill 2022--

# FELLOWSHIPS AND FUNDING

# TEACHING

*Associate Professor, Mathematics, Vassar* \hfill 1931--1941

> Teach students about math, began career in programming and largely developed design and implementation of a computer compiler.
  
*Director, Navy Programming Languages Group* \hfill 1967--1977

> She developed validation software for COBOL and its compiler as part of a COBOL standardization program for the entire Navy. Hopper advocated for the Defense Department to replace large, centralized systems with networks of small, distributed computers. Any user on any computer node could access common databases located on the network. She developed the implementation of standards for testing computer systems and components, most significantly for early programming languages such as FORTRAN and COBOL. The Navy tests for conformance to these standards led to significant convergence among the programming language dialects of the major computer vendors. In the 1980s, these tests (and their official administration) were assumed by the National Bureau of Standards (NBS), known today as the National Institute of Standards and Technology (NIST). (Source: https://en.wikipedia.org/wiki/Grace_Hopper)

# PUBLICATIONS

## **Journal Articles**

Quiterio, P. L., Nunes, L. R. O. P., Camelo, B. L., Silva, J. P., & **Carmo, M. M. I. B.** (2021). Promoção das Habilidades Sociais de Futuros Professores com foco na Educação Inclusiva. *Estudos e Pesquisa em Psicologia*. 

Quiterio, P. L., Leme, V. B. R., **Carmo, M. M. I. B.**, Silva, J. P., & Camelo, B. L. (2021). Programa de orientação familiar desenvolvido no serviço de psicologia aplicada de uma universidade pública. *Psicologia Clínica*. 

**Carmo, M. M. I. B.**, Gilla, C. G., & Quiterio, P. L. (2020). Um estudo sobre a inclusão de pessoas com deficiência no mercado de trabalho brasileiro. *Interação em Psicologia*. 

Ferreira, W. H., **Carmo, M. M. I. B.**, Silva, A. L. N., & Andrade, C. T. (2014). Effect of structure and viscosity of the components on some properties of starch-rich hybrid blends. *Carbohydrate polymers*. 

# CONFERENCE PROCEEDINGS

Silva, J. P., Quiterio, P. L., **Carmo, M. M. I. B.**, & Souza, A. B. M. (2019) A Importância do Desenvolvimento de Competências Socioemocionais em Pais e Crianças. *Anais do VII Seminário Internacional de Habilidades Sociais*.

**Carmo, M. M. I. B.**, Quiterio, P. L., Silva, J. P., & Camelo, B. L. (2019) Efeitos de Uma Intervenção de Orientação Familiar em Contexto Preventivo e Remediativo. *Anais do VII Seminário Internacional de Habilidades Sociais*. \underline{Recipient of 3rd place of the Almir Del Prette Award}

**Carmo, M. M. I. B.**, Quiterio, P. L. (2019). Grupo de Orientação Familiar: uma abordagem integrativa de psicoeducação. *Anais de Resumos da 29ª UERJ Sem Muros*.

**Carmo, M. M. I. B.**, Andrade, C. T., & Ferreira, W. H. (2013). Obtenção e propriedades de materiais híbridos parcialmente biodegradáveis. *Livro de Resumos da XXXV Jornada Giulio Massarani de Iniciação Científica, Tecnológica, Artística e Cultural - Área das Ciências Exatas*.

**Carmo, M. M. I. B.**, Figueira-Junior, M. J. M., Ferreira, W. H., Lopes, G. K., & Andrade, C. T. (2012). Caracterização morfológica e reológica de materiais híbridos de amido/polietileno/argila organifílica. *Anais do 5º Congresso da Rede Brasileira de Tecnologia do Biodiesel / 8º Congresso Brasileiro de Plantas Oleaginosas, Óleos, Gorduras e Biodiesel: Biodiesel: inovação e desenvolvimento regional*.

**Carmo, M. M. I. B.**, Figueira-Junior, M. J. M., & Andrade, C. T. (2012). Structural and viscosimetric characterization of starch/polyethylene blend. *Anais do XI Encontro da SBPMat*.

Figueira-Junior, M. J. M., **Carmo, M. M. I. B.**, Ferreira, W. H., & Andrade, C. T. (2012).  Different properties of thermoplastic starch/polyethylene blend nanocomposites with the same composition. *Anais do XI Encontro da SBPMat*.

**Carmo, M. M. I. B.**, Figueira-Junior, M. J. M., Andrade, C. T., & Ferreira, W. H. (2012). Obtenção e Caracterização Estrutural e Viscosimétrica de Biocompósitos Baseados em Amido Termoplástico. *XXXIV Jornada Giulio Massarani de Iniciação Científica, Tecnológica, Artística e Cultural da UFRJ*.

Silva, J. G., **Carmo, M. M. I. B.**, Porto, E. M., Souza, D. H. S., & Andrade, C. T. (2011). Obtenção e Caracterização de Soluções Filmogênicas para Recobrimento de Mirtilo. *9 SLACA - Simpósio Latino Americano de Ciência de Alimentos: 'Ciência de Alimentos e Qualidade de Vida: Saúde, Meio Ambiente e Sustentabilidade'*.


# POSTER PRESENTATIONS AND PRIZES

**Carmo, M. M. I. B.**, & Rafihi-Ferreira, R. (2021). The association between sleep-related cognitions, psychological flexibility, and insomnia symptoms. XVIII Congresso Brasileiro de Sono, São Paulo, Brazil. \underline{Recipient of Top Mark Award}

Conway, B. A., **Carmo, M. M. I. B.**, Toscanini, A. C., Hasan, R., & Rafihi-Ferreira, R. (2021). Personality Traits in Adults with Chronic Insomnia. XVIII Congresso Brasileiro de Sono, São Paulo, Brazil. \underline{Recipient of Top Mark Award}

Cunha, R. R. B. , Trigo, L. O., **Carmo, M. M. I. B.**, Rafihi-Ferreira, R., & Toscanini, A. C. (2021). Chronotype Influence on the Sleep Pattern and Physical/Academic Performance of Medical Students in the State of São Paulo, Brazil. XVIII Congresso Brasileiro de Sono, São Paulo, Brazil.

Trigo, L. O., Cunha, R. R. B. , **Carmo, M. M. I. B.**, Rafihi-Ferreira, R., & Toscanini, A. C. (2021). Sleep Pattern, Cellphone Use and Grade Point Average in São Paulo Medical Students. XVIII Congresso Brasileiro de Sono, São Paulo, Brazil.

Silva, D. A., Souza, J. F., **Carmo, M. M. I. B.**, Quiterio, P. L. (2021). Programas de orientação familiar: intervenções com populações clínicas e não clínicas. 51ª Reunião Anual da Sociedade Brasileira de Psicologia, Rio de Janeiro, Brazil.

**Carmo, M. M. I. B.**, & Quiterio, P. L. (2019). Avaliação Psicológica de um Adolescente com Deficiência Intelectual em uma Clínica-Escola. VIII Mostra Carioca de Neuropsicologia Clínica, Rio de Janeiro, Brazil.

**Carmo, M. M. I. B.**, Gilla, C. G., & Quiterio, P. L. (2018). Um estudo sobre a inclusão de pessoas com deficiência no mercado de trabalho brasileiro. 12ª Mostra Regional de Práticas em Psicologia, Rio de Janeiro, Brazil.

**Carmo, M. M. I. B.**, & Quiterio, P. L. (2018). Grupo de Orientação Familiar: Uma abordagem integrativa de psicoeducação. 17ª Semana de Graduação UERJ, Rio de Janeiro, Brazil.

Camelo, B. L., Gilla, C. G., Paz, G. R. A., Silva, J. P., Oliveira, M. V., **Carmo, M. M. I. B.**, & Quiterio, P. L. (2018). Grupo de Orientação Familiar: Programa de Promoção de Habilidades Sociais Educativas Parentais. XII Semana de Psicologia UERJ, Rio de Janeiro, Brazil.

Quiterio, P. L., & **Carmo, M. M. I. B.**. (2018). PPHS - Programa de Promoção das Habilidades Sociais de alunos sem fala articulada tendo graduandos em Psicologia como interlocutores. 21ª Mostra de Extensão UERJ, Rio de Janeiro, Brazil.

Quiterio, P. L., **Carmo, M. M. I. B.**, Barbosa, H. S., Falcone, J. F., Campello, F., Dias, R. (2018). Desenvolvimento de um grupo de orientação familiar por estudantes de Psicologia. 48ª Reunião Anual da Sociedade Brasileira de Psicologia, Rio de Janeiro, Brazil.

**Carmo, M. M. I. B.**, Camelo, B. L., Silva, J. P., & Quiterio, P. L. (2018). Avaliação de um Grupo de Orientação Familiar. VII Congresso Brasileiro de Terapia Cognitiva da Infância e Adolescência, Bahia, Brazil. \underline{Recipient of 3rd place in Best Posters Award}

Figueira-Junior, M. J. M., **Carmo, M. M. I. B.**, Andrade, C. T., & Ferreira, W. H. (2012). Obtenção e caracterização estrutural e viscosimétrica de biocompósitos baseados em amido termoplástico. XXXIV Jornada Giulio Massarani de Iniciação Científica, Tecnológica, Artística e Cultural da UFRJ, Rio de Janeiro, Brazil.

# AWARDS

**1964**  *Society of Women Engineers Achievement Award*, the Society’s highest honor, “In recognition of her significant contributions to the burgeoning computer industry as an engineering manager and originator of automatic programming systems.”

**1969**  *Data Processing Management Association Man of the Year* (now called the Distinguished Information Sciences Award)

**1973** *Distinguished Fellow of the British Computer Society*. First American and the first woman of any nationality to be given award.

**1982** *American Association of University Women Achievement Award*

**1987** *Computer History Museum Fellow Award Recipient* First to receive this award, for contributions to the development of programming languages, for standardization efforts, and for lifelong naval service.

**1991**: *National Medal of Technology*

**1996**: *USS Hopper (DDG-70) was launched*. Nicknamed Amazing Grace, it is on a very short list of U.S. military vessels named after women.

**2009**: The Department of Energy's National Energy Research Scientific Computing Center named its flagship system "Hopper"

**2016**: Posthumously awarded a *Presidential Medal of Freedom* for her accomplishments in the field of computer science

# SKILLS

*Programming*: R (proficient), Python (familiar)

*Tools*: Git, RStudio's Shiny, LaTeX (familiar), SPSS, JASP, JAMOVI, Zotero

*Statistics Training*